### ISSUE TITLE
Add ability to customize columns and data to be included in Sheet List

### ISSUE THREAD

**Issue by bretleasure** [bretleasure/SheetList#2]

**Comment by JMadore14** [comment]
Is this something that will be done in the near future? It would be beneficial for some of us to be able to include sheet revisions and revision dates.

**Comment by bretleasure** [comment]
Would you be using the Addin's UI button to create the sheet list or the API to create it with code?

**Comment by JMadore14** [comment]
Ideally we would be able to use the Addin's UI button.

We evidently need to modify the code to accomplish this and we understand
that we can download the original code files but we are unsure where to
save them on our harddrive after and how to compile it.

Regards,
*Jacob Madore*, P.Eng
President, JLM Mechanical
Mobile: +1-(705)-363-8883

**Comment by JMadore14** [comment]
I'm following up on this item.

Would it be a possibility to modify the add-in to include the project number and sheet revision?

**Comment by bretleasure** [comment]
@JMadore14 I have started on an update that will allow customizing the columns for the table. However, I do this on the side whenever I get time so I don't have an estimate on when this will be completed.

**Comment by JMadore14** [comment]
No problem, I will attempt to work on it from my end as well.

**Comment by JMadore14** [comment]
Everything works as it should! We will try to find a way to make the columns combine such that the project number, sheet number and revision can be read in one continuous line.

**Comment by JMadore14** [comment]
Bret, is there a way to give us the ability to fetch a prompted entry and include it in the drawing list? For example, let's say we start a package at drawing 100, the "Sheet Number" value is no longer useful as it always starts at 1. We realize that we can customize the sheet name, but we want to maintain this flexibility and use it for the drawing "Description".

In Revit, our list looks like this:

![SheetListRevit1](https://github.com/user-attachments/assets/965530f2-3394-43f2-a4eb-34ceed3f795f)

And we can modify it easily with the schedule editor as seen below:

![image](https://github.com/user-attachments/assets/a9743237-f64a-4022-aef7-5f5f8e6f3576)

Sheet name and number are parameters in Revit and I think we can solve our issue by allowing us to combine columns like Revit, see below:

![image](https://github.com/user-attachments/assets/b6200c75-c4d3-43b0-a973-d9522edfddee)

Or by allowing us to fetch prompted entries.

Any help or guidance is appreciated.

**Comment by bretleasure** [comment]
> Bret, is there a way to give us the ability to fetch a prompted entry and include it in the drawing list? For example, let's say we start a package at drawing 100, the "Sheet Number" value is no longer useful as it always starts at 1. We realize that we can customize the sheet name, but we want to maintain this flexibility and use it for the drawing "Description".
> 
> In Revit, our list looks like this:
> 
> ![SheetListRevit1](https://private-user-images.githubusercontent.com/173733111/365450953-965530f2-3394-43f2-a4eb-34ceed3f795f.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NjMxMDEsIm5iZiI6MTczNDQ2MjgwMSwicGF0aCI6Ii8xNzM3MzMxMTEvMzY1NDUwOTUzLTk2NTUzMGYyLTMzOTQtNDNmMi1hNGViLTM0Y2VlZDNmNzk1Zi5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxOTEzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYmVkMzAzN2NiMDEwNjFiYjMxYzkwNmY2MTYxNDcwNzQ4YjM5ZGI5YzEyZmIyZGMxNTk1ZDBmM2NkYjVmNDNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vBJ-7qSx69dcNkbbbFNSNr4gF0Ex7h4KkMnqJh_9hFE)
> 
> And we can modify it easily with the schedule editor as seen below:
> 
> ![image](https://private-user-images.githubusercontent.com/173733111/365450994-a9743237-f64a-4022-aef7-5f5f8e6f3576.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NjMxMDEsIm5iZiI6MTczNDQ2MjgwMSwicGF0aCI6Ii8xNzM3MzMxMTEvMzY1NDUwOTk0LWE5NzQzMjM3LWY2NGEtNDAyMi1hZWY3LTVmNWY4ZTZmMzU3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxOTEzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjliMTdiNTQ0YTcxOTFiMmI0MWE0OGZkYjgwMTEwZTk0NmU3Y2VhNzE2OTM3ZTE0MGUxZWNjMTdlNWI2OGFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.r_Ge-amjQAeBal5cFPIJX2F6sWH9P0dlTXgmEOaYwhk)
> 
> Sheet name and number are parameters in Revit and I think we can solve our issue by allowing us to combine columns like Revit, see below:
> 
> ![image](https://private-user-images.githubusercontent.com/173733111/365451035-b6200c75-c4d3-43b0-a973-d9522edfddee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NjMxMDEsIm5iZiI6MTczNDQ2MjgwMSwicGF0aCI6Ii8xNzM3MzMxMTEvMzY1NDUxMDM1LWI2MjAwYzc1LWM0ZDMtNDNiMC1hOTczLWQ5NTIyZWRmZGRlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxOTEzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjk4ODczODIwYTQ2YzI5NDM0OWY3NzE1NWIwYTVkY2EwYzBkZjA5YTEzYjAxZWRlYzZiZGEwOTIxMmJkY2ZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9f3PPPWrsjV2v9D5BLzLROaB6Ars99ijnuVbxzVuCC4)
> 
> Or by allowing us to fetch prompted entries.
> 
> Any help or guidance is appreciated.

#20
